# Generated by Django 2.0.7 on 2018-07-19 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180719_0511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='auth_key',
            new_name='auth_token',
        ),
    ]
