# Generated by Django 2.0.7 on 2018-07-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scavengerhunts', '0002_auto_20180721_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scavengerhunt',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
