# Generated by Django 2.0.7 on 2018-07-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scavengerhunts', '0003_auto_20180721_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scavengerhunt',
            name='username',
        ),
    ]
