# Generated by Django 2.0.7 on 2018-07-21 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scavengerhunts', '0004_remove_scavengerhunt_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='scavengerhunt',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scavengerhunt',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
